export const PHONE = "(613) 617-4238";
export const PHONE_HREF = "tel:6136174238";
export const SMS_HREF = "sms:6136174238";
export const EMAIL = "info@ottawagaragedoorrepair.ca";
export const FACEBOOK_URL = "https://www.facebook.com/profile.php?id=61588598975402";
export const INSTAGRAM_URL = "https://www.instagram.com/ottawagaragedoor/";
export const BUSINESS_NAME = "Ottawa - GDR";
export const TAGLINE = "Ottawa's #1 Rated Garage Door Service";

export const services = [
  { slug: "spring-replacement", icon: "🔩", title: "Spring Replacement", image: null, shortDesc: "Broken torsion or extension springs replaced same day. We use 10,000-cycle rated springs and replace both sides when needed so your door runs smoothly and safely. Most jobs done in under an hour.", fullDesc: "Garage door springs are under extreme tension and are the most common cause of door failure in Ottawa. Cold snaps, age, and daily use all take a toll — when one spring breaks, the other is usually close behind. We always replace both torsion or extension springs together for balanced, long-lasting operation and to prevent a second call in weeks. Our licensed technicians use 10,000-cycle rated hardware, proper winding bars, and safety procedures; we never cut corners. Most spring replacements are completed in under an hour. We carry a full range of springs on every truck for same-day service across Kanata, Barrhaven, Orleans, Nepean, Stittsville, and all Ottawa neighbourhoods. Written quote before we start; 1-year warranty on parts and labour.", price: "$220–350", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door spring repair Ottawa", "broken torsion spring Ottawa", "garage door spring replacement cost Ottawa"] },
  { slug: "opener-repair", icon: "⚙️", title: "Opener Repair & Installation", image: null, shortDesc: "All major brands serviced — LiftMaster, Chamberlain, Genie, Craftsman, Marantec. Remote programming, sensor alignment, and full motor repair or replacement. Same-day diagnosis and fix.", fullDesc: "Whether your opener is grinding, not responding to remotes, or completely dead, we diagnose and fix every major brand. We repair wall consoles and keypads, reprogram remotes and vehicle homelink, align safety sensors so the door reverses correctly, and replace worn gears or entire units. Opener installation from $195+; gear replacement from $250. We also supply and install new belt-drive and smart openers from $650 (model-dependent), with full warranty on parts and labour. Our trucks carry common opener parts so many repairs are done in one visit. We serve all Ottawa areas with same-day or next-day booking.", price: "From $195", time: "1–3 hours", warranty: "1 Year", keywords: ["garage door opener repair Ottawa", "LiftMaster repair Ottawa", "smart garage door opener Ottawa"] },
  { slug: "opener-gear-replacement", icon: "⚙️", title: "Opener Gear Replacement", image: null, shortDesc: "Worn drive gear repaired — motor humming but door not moving? We replace the gear assembly so your opener runs quietly and reliably again, often for years.", fullDesc: "Grinding or clicking with the motor running usually means worn plastic or metal drive gears inside the opener. We replace the gear assembly with quality parts so your opener runs quietly and reliably. This fix often extends the life of your opener by years and costs a fraction of a full replacement. We stock common gear kits and can usually complete the job the same day. Same-day service available across Ottawa; 1-year warranty on the repair.", price: "From $250", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door opener gear repair Ottawa", "opener gear replacement Ottawa"] },
  { slug: "emergency-repair", icon: "🚨", title: "24/7 Emergency Repair", image: null, shortDesc: "Stuck, off-track, or broken door? We come to you now — 24/7 across Ottawa. Under 90 minutes to your door. No overtime premium.", fullDesc: "A garage door emergency doesn't wait for business hours — and neither do we. Our emergency technicians are available 24 hours a day, 7 days a week across Ottawa. Stuck door, off-track panel, snapped spring, or broken cable — we arrive in under 90 minutes with the parts and expertise to get you secure. We carry springs, cables, rollers, and opener parts on every truck so most emergencies are fixed on the first visit. No overtime premium; transparent pricing before we start. We serve Kanata, Barrhaven, Orleans, Nepean, Stittsville, and every Ottawa neighbourhood.", price: "From $199", time: "Same day", warranty: "90 Days", keywords: ["emergency garage door repair Ottawa", "24 hour garage door repair Ottawa", "garage door stuck Ottawa"] },
  { slug: "new-door-installation", icon: "🚪", title: "New Door Installation", image: null, shortDesc: "Steel, wood, glass & carriage-house styles. Full supply & install with free in-home estimates, 5-year warranty, and removal of your old door.", fullDesc: "Upgrade your home's curb appeal and energy efficiency with a new garage door. We supply and install residential and commercial doors in every style — steel, wood, composite, glass, and carriage-house. Insulated options (including R-value upgrades) help cut heating costs in Ottawa winters and protect vehicles and storage. Free in-home estimates; transparent pricing; 5-year warranty on our installation. We handle removal of your old door, disposal, and full cleanup. Serving all Ottawa areas with professional installation and no hidden fees.", price: "$1,800–4,500", time: "4–8 hours", warranty: "5 Years", keywords: ["garage door installation Ottawa", "new garage door Ottawa", "carriage house garage door Ottawa"] },
  { slug: "cable-repair", icon: "🔧", title: "Cable Repair", image: null, shortDesc: "Snapped or frayed lift cables replaced safely by licensed technicians. We always replace both cables for balanced, safe operation and long-lasting results.", fullDesc: "Broken or frayed lift cables cause the door to fall unevenly, strain the opener, and are dangerous to ignore. We replace both cables simultaneously with quality hardware so your door runs smoothly and safely — replacing only one cable leaves the other as a weak point and can lead to another failure soon. Our technicians are trained to work with high-tension cable systems; we use the correct cable type and length for your door size and weight. We never leave you with a half-fixed door. Most cable repairs are completed in 1–2 hours. Same-day service across Ottawa; 1-year warranty on parts and labour.", price: "$170–250", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door cable repair Ottawa", "broken garage door cable Ottawa"] },
  { slug: "panel-repair", icon: "🏗️", title: "Panel Repair", image: null, shortDesc: "Dented or damaged panels repaired — we fix the damage you have instead of selling a full replacement. Honest assessment every time.", fullDesc: "We don't replace whole panels unless necessary; we repair damaged sections to restore your door's look and function at a fraction of the cost of a new door or full panel swap. Dents from vehicles, dings from weather or impact, and rust or wear at the bottom can often be fixed in one visit. Panel repair starts at $170. We give you an honest assessment: if a full panel or new door is the right call for safety or appearance, we'll say so. No pressure to upsell. Serving Ottawa with same-day or next-day service.", price: "From $170", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door panel repair Ottawa", "dented garage door Ottawa"] },
  { slug: "weatherstripping", icon: "❄️", title: "Weatherstripping & Insulation", image: null, shortDesc: "Keep Ottawa winters out. Bottom seal, threshold, and side seals — full weather barrier and insulation upgrades. Cuts drafts and protects your garage.", fullDesc: "Ottawa winters are brutal on garage doors. Gaps and worn seals let in cold, snow, and moisture, driving up heating costs and exposing your garage and vehicle to the elements. We replace bottom seals, threshold seals, and side seals with durable materials that stand up to -30°C and road salt. We can also add or upgrade insulation on existing doors to improve R-value. Weather seal replacement from $250; 2-year warranty on our seal work. Many Ottawa homeowners schedule this before winter or after noticing drafts or ice inside the garage.", price: "From $250", time: "1–2 hours", warranty: "2 Years", keywords: ["garage door weatherstripping Ottawa", "insulated garage door Ottawa"] },
  { slug: "maintenance-tune-up", icon: "📋", title: "Maintenance Tune-Up", image: null, shortDesc: "Full 21-point inspection, lubrication, and adjustment. Catch small issues before they become costly repairs. Recommended annually.", fullDesc: "Preventive maintenance is the cheapest garage door repair. Our 21-point tune-up includes lubricating all moving parts (hinges, rollers, springs, tracks), testing safety sensors and auto-reverse, adjusting spring tension and track alignment, and checking cables and brackets for wear. We give you a clear report and recommendations — no surprises. Many Ottawa homeowners book this annually to avoid winter breakdowns and extend the life of their door and opener. $150; typically 45 minutes. Available across all Ottawa neighbourhoods.", price: "$150", time: "45 mins", warranty: "3 Months", keywords: ["garage door maintenance Ottawa", "garage door tune up Ottawa"] },
];

export const areas = [
  { slug: "kanata", name: "Kanata", desc: "Fast response across Kanata, Stittsville & surrounding areas", localNote: "Serving Bridlewood, Morgan's Grant, Beaverbrook & all Kanata communities." },
  { slug: "barrhaven", name: "Barrhaven", desc: "Serving Barrhaven, Riverside South & Manotick", localNote: "We know Barrhaven's newer subdivisions and fast-growing communities well." },
  { slug: "nepean", name: "Nepean", desc: "Full coverage across Nepean & Bells Corners", localNote: "Nepean's mix of older homes and new builds — we stock parts for all door generations." },
  { slug: "orleans", name: "Orleans", desc: "Full coverage across Orleans & Navan", localNote: "Serving all Orleans communities including Chapel Hill, Fallingbrook & Cardinal Creek." },
  { slug: "stittsville", name: "Stittsville", desc: "Stittsville & Carleton Place", localNote: "Serving Stittsville and Carleton Place. We arrive in under 90 min everywhere in Ottawa." },
  { slug: "gloucester", name: "Gloucester", desc: "Serving Gloucester, Alta Vista & Hunt Club", localNote: "Fast coverage of Gloucester's dense residential areas." },
  { slug: "manotick", name: "Manotick", desc: "Rural and estate garage door specialists", localNote: "Large and custom door installations common in Manotick estate homes." },
  { slug: "alta-vista", name: "Alta Vista", desc: "Central Ottawa coverage including Alta Vista & Old Ottawa East", localNote: "Serving established Alta Vista neighbourhoods with older door systems." },
  { slug: "hunt-club", name: "Hunt Club", desc: "Serving Hunt Club, South Keys & Airport area", localNote: "Commercial and residential service in the Hunt Club corridor." },
  { slug: "riverside-south", name: "Riverside South", desc: "New home specialists in Riverside South & Findlay Creek", localNote: "Many new builds in Riverside South — we're familiar with all new construction door brands." },
  { slug: "westboro", name: "Westboro", desc: "Serving Westboro, Hintonburg & urban Ottawa", localNote: "Urban Ottawa specialist — tight laneways and heritage homes, no problem." },
  { slug: "vanier", name: "Vanier", desc: "Vanier, New Edinburgh & Overbrook", localNote: "Central-east Ottawa. We arrive in under 90 min in every area." },
  { slug: "rockcliffe-park", name: "Rockcliffe Park", desc: "Rockcliffe Park & New Edinburgh", localNote: "Serving Rockcliffe Park and nearby communities." },
  { slug: "findlay-creek", name: "Findlay Creek", desc: "Findlay Creek & Riverside South", localNote: "New development specialist. Findlay Creek and Riverside South coverage." },
  { slug: "carp", name: "Carp", desc: "Carp, Kanata North & West Ottawa", localNote: "West Ottawa rural and village service. Carp and surrounding areas." },
  { slug: "dunrobin", name: "Dunrobin", desc: "Dunrobin & West Carleton", localNote: "West Carleton coverage. Dunrobin and rural west Ottawa." },
  { slug: "richmond", name: "Richmond", desc: "Richmond, North Gower & rural South Ottawa", localNote: "Rural south Ottawa. Richmond village and surrounding areas." },
  { slug: "greely", name: "Greely", desc: "Greely & growing South Ottawa", localNote: "South Ottawa growth corridor. Greely and Findlay Creek area." },
  { slug: "sandy-hill", name: "Sandy Hill", desc: "Sandy Hill, University area & downtown east", localNote: "Central Ottawa. Sandy Hill, University of Ottawa area and downtown east." },
  { slug: "glebe", name: "Glebe", desc: "Glebe, Old Ottawa South & Lansdowne", localNote: "Central Ottawa. Glebe, Old Ottawa South and Lansdowne area." },
  { slug: "beacon-hill", name: "Beacon Hill", desc: "Beacon Hill, Cyrville & Gloucester North", localNote: "East Ottawa. Beacon Hill, Cyrville and north Gloucester." },
  { slug: "blackburn-hamlet", name: "Blackburn Hamlet", desc: "Blackburn Hamlet & Orleans east", localNote: "East Ottawa. Blackburn Hamlet and eastern Orleans." },
  { slug: "cumberland", name: "Cumberland", desc: "Cumberland, Orleans & Navan", localNote: "East Ottawa village. Cumberland and rural Orleans." },
  { slug: "carleton-place", name: "Carleton Place", desc: "Carleton Place & Ottawa Valley", localNote: "Serving Carleton Place and surrounding Ottawa Valley communities." },
  /* Communities within ~40 min drive of Ottawa */
  { slug: "embrun", name: "Embrun", desc: "Embrun, Russell Township & east Ottawa region", localNote: "Serving Embrun and Russell Township. Same-day garage door service from Ottawa." },
  { slug: "russell", name: "Russell", desc: "Russell village, Russell Township & surrounding area", localNote: "Russell and area — we drive out from Ottawa for repairs and installations." },
  { slug: "metcalfe", name: "Metcalfe", desc: "Metcalfe, Osgoode & rural South Ottawa", localNote: "Metcalfe and Osgoode area. Rural and village garage door service." },
  { slug: "kemptville", name: "Kemptville", desc: "Kemptville & North Grenville", localNote: "Kemptville and North Grenville. Full garage door repair and installation from Ottawa." },
  { slug: "arnprior", name: "Arnprior", desc: "Arnprior & Ottawa Valley west", localNote: "Arnprior and the Ottawa Valley. Same-day service from our Ottawa base." },
  { slug: "almonte", name: "Almonte", desc: "Almonte, Mississippi Mills & west Ottawa", localNote: "Almonte and Mississippi Mills. We serve the valley west of Ottawa." },
  { slug: "casselman", name: "Casselman", desc: "Casselman & Prescott-Russell east", localNote: "Casselman and Prescott-Russell. East-end Ottawa and surrounding communities." },
  { slug: "rockland", name: "Rockland", desc: "Rockland, Clarence-Rockland & east Ottawa", localNote: "Rockland and Clarence-Rockland. Bilingual service available." },
  { slug: "navan", name: "Navan", desc: "Navan & rural east Ottawa", localNote: "Navan village and rural east Ottawa. Fast response from Orleans/Gloucester." },
  { slug: "smiths-falls", name: "Smiths Falls", desc: "Smiths Falls & Rideau region", localNote: "Smiths Falls and the Rideau area. Garage door repair and installation within 40 min of Ottawa." },
  { slug: "winchester", name: "Winchester", desc: "Winchester & North Dundas", localNote: "Winchester and North Dundas. South Ottawa and rural SDG coverage." },
  { slug: "limoges", name: "Limoges", desc: "Limoges & Prescott-Russell", localNote: "Limoges and Prescott-Russell. East of Ottawa, same-day service." },
  { slug: "constance-bay", name: "Constance Bay", desc: "Constance Bay & West Carleton", localNote: "Constance Bay and West Carleton. West Ottawa and river communities." },
  { slug: "osgoode", name: "Osgoode", desc: "Osgoode village & rural South Ottawa", localNote: "Osgoode and rural south Ottawa. Village and country garage door service." },
];

export const testimonials = [
  { name: "Mike R.", area: "Kanata", stars: 5, date: "January 2026", text: "Called at 11pm when my spring snapped and I couldn't get my car out for work. Ottawa - GDR had a tech here within 75 minutes and fixed it in under an hour. Incredible service. Will never use anyone else." },
  { name: "Robert H.", area: "Kanata", stars: 5, date: "February 2026", text: "Door came off the track on a Sunday morning. Ottawa - GDR was at my house within an hour. Fixed, tested, and cleaned up in 90 minutes flat. Couldn't believe how fast and professional it was." },
  { name: "Sarah T.", area: "Barrhaven", stars: 5, date: "December 2025", text: "Garage door stopped working during a -30°C cold snap. Ottawa - GDR came the same morning, diagnosed the frozen opener, and had us back up in no time. Price was exactly what they quoted." },
  { name: "James L.", area: "Nepean", stars: 5, date: "February 2026", text: "Had 3 quotes to replace my entire door. Ottawa - GDR showed me I only needed a panel and spring, saving me over $1,200. Honest company that puts the customer first." },
  { name: "Nadia B.", area: "Orleans", stars: 5, date: "January 2026", text: "Needed an emergency repair on a Saturday night in Fallingbrook. Ottawa - GDR answered immediately and arrived within 90 minutes. Friendly tech, clean work, fair price. Amazing." },
  { name: "David M.", area: "Gloucester", stars: 5, date: "January 2026", text: "Second time using Ottawa - GDR. Both times: on time, transparent pricing, quality work. They noticed my cables were fraying and showed me before replacing. That proactive approach is rare." },
];

export const faqs = [
  { q: "How much does garage door repair cost in Ottawa?", a: "Spring replacement $220–350, cable repair $170–250, maintenance tune-up $150, panel repair from $170 (we don't replace panels). Opener installation from $195; opener gear replacement from $250; new openers supply & install from $650 (model-dependent). New garage doors from $1,800–4,500 (size and model). We always provide a full written quote before any work begins." },
  { q: "How fast can you respond to an emergency?", a: "We arrive in under 90 minutes everywhere in Ottawa — same promise in every neighbourhood." },
  { q: "Do you offer a warranty on your repairs?", a: "Yes. All parts come with a minimum 1-year warranty and all labour is guaranteed for 90 days. New door installations carry a 5-year warranty." },
  { q: "Can I get same-day service?", a: "Absolutely. Same-day service is available 7 days a week, 9AM–9PM. We stock the most common parts on our trucks so most repairs are completed in one visit." },
  { q: "Are you licensed and insured?", a: "Yes. Ottawa - GDR is fully licensed in Ontario and carries $2 million in liability insurance." },
  { q: "What brands do you work with?", a: "We service all major brands including LiftMaster, Chamberlain, Genie, Craftsman, Marantec, Garaga, Clopay, Wayne Dalton, and more." },
];

/** Gallery: copy images from garagedoorsolutionsottawa.ca/gallery into public/gallery/ as 1.jpg, 2.jpg, etc. Or use full URLs (domain allowed in next.config). */
export const galleryImages = [
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/IMG-20260206-WA0000(1).jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'New insulated garage door Kanata', caption: 'New insulated garage door in Kanata' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/IMG-20260206-WA0001(8).jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Weather stripping garage door Ottawa', caption: 'Weather stripping' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/blob-2c95119.png/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Garage door installed Barrhaven', caption: 'Garage door installed in Barrhaven' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/20251025_142148.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Two garage doors replaced Nepean', caption: '2 doors replaced in Nepean' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/20250124_095313.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'New door and opener Greely', caption: 'New door and opener in Greely' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/20250121_090341.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Opener gear replacement Ottawa', caption: 'Gear replacement' },
];

export const blogPosts = [
  { slug: "garage-door-repair-cost-ottawa", title: "How Much Does Garage Door Repair Cost in Ottawa? (2026 Guide)", excerpt: "Complete pricing breakdown for every common garage door repair in Ottawa.", date: "February 10, 2026", readTime: "5 min read", category: "Pricing" },
  { slug: "broken-spring-ottawa-what-to-do", title: "Broken Garage Door Spring in Ottawa? Here's What To Do", excerpt: "Step-by-step guide on how to identify a broken spring and stay safe.", date: "January 28, 2026", readTime: "4 min read", category: "DIY Tips" },
  { slug: "garage-door-not-opening-cold-weather", title: "Garage Door Not Opening in Cold Weather? Ottawa Winter Fixes", excerpt: "Ottawa's brutal winters wreak havoc on garage doors. Here's why and how to fix it.", date: "January 15, 2026", readTime: "6 min read", category: "Winter Tips" },
  { slug: "best-insulated-garage-doors-ottawa", title: "Best Insulated Garage Doors for Ottawa Winters (2026 Reviews)", excerpt: "We compare the top insulated garage door brands available in Ottawa.", date: "December 20, 2025", readTime: "7 min read", category: "Buying Guide" },
  { slug: "how-long-do-garage-door-springs-last", title: "How Long Do Garage Door Springs Last? Ottawa Homeowner Guide", excerpt: "Most springs are rated for 10,000 cycles. Find out when to replace before they snap.", date: "December 5, 2025", readTime: "4 min read", category: "Maintenance" },
  { slug: "smart-garage-door-opener-ottawa", title: "Best Smart Garage Door Openers in Ottawa (2026)", excerpt: "We review the top WiFi-enabled openers available and installed in Ottawa.", date: "November 18, 2025", readTime: "8 min read", category: "Smart Home" },
];
