export const PHONE = "(613) 617-4238";
export const PHONE_HREF = "tel:6136174238";
export const EMAIL = "info@ottawagaragedoorrepair.ca";
export const BUSINESS_NAME = "Ottawa - GDR";
export const TAGLINE = "Ottawa's #1 Rated Garage Door Service";

export const services = [
  { slug: "spring-replacement", icon: "🔩", title: "Spring Replacement", shortDesc: "Broken torsion or extension springs replaced same day.", fullDesc: "Garage door springs are under extreme tension and are the most common cause of door failure. Our licensed technicians replace torsion and extension springs safely and quickly — most repairs done in under an hour.", price: "$220–350", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door spring repair Ottawa", "broken torsion spring Ottawa", "garage door spring replacement cost Ottawa"] },
  { slug: "opener-repair", icon: "⚙️", title: "Opener Repair & Installation", shortDesc: "All major brands serviced — LiftMaster, Chamberlain, Genie.", fullDesc: "Whether your opener is grinding, not responding to remotes, or completely dead, we diagnose and fix all brands. Opener installation from $195+. Opener gear replacement from $250. We also supply and install new openers from $650 (model-dependent).", price: "From $195", time: "1–3 hours", warranty: "1 Year", keywords: ["garage door opener repair Ottawa", "LiftMaster repair Ottawa", "smart garage door opener Ottawa"] },
  { slug: "opener-gear-replacement", icon: "⚙️", title: "Opener Gear Replacement", shortDesc: "Worn drive gear repaired — motor humming but door not moving.", fullDesc: "Grinding or clicking with the motor running usually means worn gears. We replace the drive gear assembly so your opener runs quietly again.", price: "From $250", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door opener gear repair Ottawa", "opener gear replacement Ottawa"] },
  { slug: "emergency-repair", icon: "🚨", title: "24/7 Emergency Repair", shortDesc: "Stuck, off-track, or broken door? We come to you now.", fullDesc: "A garage door emergency doesn't wait for business hours — and neither do we. Our emergency technicians are available 24 hours a day, 7 days a week across Ottawa.", price: "From $199", time: "Same day", warranty: "90 Days", keywords: ["emergency garage door repair Ottawa", "24 hour garage door repair Ottawa", "garage door stuck Ottawa"] },
  { slug: "new-door-installation", icon: "🚪", title: "New Door Installation", shortDesc: "Steel, wood, glass & carriage-house styles. Full supply & install.", fullDesc: "Upgrade your home's curb appeal with a stunning new garage door. We supply and install residential and commercial doors in every style. Free in-home estimates.", price: "$1,800–4,500", time: "4–8 hours", warranty: "5 Years", keywords: ["garage door installation Ottawa", "new garage door Ottawa", "carriage house garage door Ottawa"] },
  { slug: "cable-repair", icon: "🔧", title: "Cable Repair", shortDesc: "Snapped or frayed cables replaced safely by our licensed technicians.", fullDesc: "Broken lift cables cause the door to fall unevenly and are dangerous to ignore. We replace both cables simultaneously to ensure balanced operation.", price: "$170–250", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door cable repair Ottawa", "broken garage door cable Ottawa"] },
  { slug: "panel-repair", icon: "🏗️", title: "Panel Repair", shortDesc: "Dented or damaged panels repaired — we repair only, we don't replace panels.", fullDesc: "We don't replace panels; we repair damaged sections to restore your door's look and function. Panel repair starts at $170.", price: "From $170", time: "1–2 hours", warranty: "1 Year", keywords: ["garage door panel repair Ottawa", "dented garage door Ottawa"] },
  { slug: "weatherstripping", icon: "❄️", title: "Weatherstripping & Insulation", shortDesc: "Keep Ottawa winters out. Full seal and insulation upgrades.", fullDesc: "Ottawa winters are brutal. Proper weatherstripping and door insulation saves significantly on heating costs and protects your garage contents. Weather seal replacement from $250.", price: "From $250", time: "1–2 hours", warranty: "2 Years", keywords: ["garage door weatherstripping Ottawa", "insulated garage door Ottawa"] },
  { slug: "maintenance-tune-up", icon: "📋", title: "Maintenance Tune-Up", shortDesc: "Full 21-point inspection, lubrication, and adjustment service.", fullDesc: "Preventive maintenance is the cheapest garage door repair. Our 21-point tune-up includes lubricating all moving parts, testing safety sensors, and adjusting spring tension.", price: "$150", time: "45 mins", warranty: "3 Months", keywords: ["garage door maintenance Ottawa", "garage door tune up Ottawa"] },
];

export const areas = [
  { slug: "kanata", name: "Kanata", desc: "Fast response across Kanata, Stittsville & surrounding areas", localNote: "Serving Bridlewood, Morgan's Grant, Beaverbrook & all Kanata communities." },
  { slug: "barrhaven", name: "Barrhaven", desc: "Serving Barrhaven, Riverside South & Manotick", localNote: "We know Barrhaven's newer subdivisions and fast-growing communities well." },
  { slug: "nepean", name: "Nepean", desc: "Full coverage across Nepean & Bells Corners", localNote: "Nepean's mix of older homes and new builds — we stock parts for all door generations." },
  { slug: "orleans", name: "Orleans", desc: "Full coverage across Orleans & Navan", localNote: "Serving all Orleans communities including Chapel Hill, Fallingbrook & Cardinal Creek." },
  { slug: "stittsville", name: "Stittsville", desc: "Stittsville & Carleton Place", localNote: "Serving Stittsville and Carleton Place. We arrive in under 90 min everywhere in Ottawa." },
  { slug: "gloucester", name: "Gloucester", desc: "Serving Gloucester, Alta Vista & Hunt Club", localNote: "Fast coverage of Gloucester's dense residential areas." },
  { slug: "manotick", name: "Manotick", desc: "Rural and estate garage door specialists", localNote: "Large and custom door installations common in Manotick estate homes." },
  { slug: "alta-vista", name: "Alta Vista", desc: "Central Ottawa coverage including Alta Vista & Old Ottawa East", localNote: "Serving established Alta Vista neighbourhoods with older door systems." },
  { slug: "hunt-club", name: "Hunt Club", desc: "Serving Hunt Club, South Keys & Airport area", localNote: "Commercial and residential service in the Hunt Club corridor." },
  { slug: "riverside-south", name: "Riverside South", desc: "New home specialists in Riverside South & Findlay Creek", localNote: "Many new builds in Riverside South — we're familiar with all new construction door brands." },
  { slug: "westboro", name: "Westboro", desc: "Serving Westboro, Hintonburg & urban Ottawa", localNote: "Urban Ottawa specialist — tight laneways and heritage homes, no problem." },
  { slug: "vanier", name: "Vanier", desc: "Vanier, New Edinburgh & Overbrook", localNote: "Central-east Ottawa. We arrive in under 90 min in every area." },
  { slug: "rockcliffe-park", name: "Rockcliffe Park", desc: "Rockcliffe Park & New Edinburgh", localNote: "Serving Rockcliffe Park and nearby communities." },
  { slug: "findlay-creek", name: "Findlay Creek", desc: "Findlay Creek & Riverside South", localNote: "New development specialist. Findlay Creek and Riverside South coverage." },
  { slug: "carp", name: "Carp", desc: "Carp, Kanata North & West Ottawa", localNote: "West Ottawa rural and village service. Carp and surrounding areas." },
  { slug: "dunrobin", name: "Dunrobin", desc: "Dunrobin & West Carleton", localNote: "West Carleton coverage. Dunrobin and rural west Ottawa." },
  { slug: "richmond", name: "Richmond", desc: "Richmond, North Gower & rural South Ottawa", localNote: "Rural south Ottawa. Richmond village and surrounding areas." },
  { slug: "greely", name: "Greely", desc: "Greely & growing South Ottawa", localNote: "South Ottawa growth corridor. Greely and Findlay Creek area." },
  { slug: "sandy-hill", name: "Sandy Hill", desc: "Sandy Hill, University area & downtown east", localNote: "Central Ottawa. Sandy Hill, University of Ottawa area and downtown east." },
  { slug: "glebe", name: "Glebe", desc: "Glebe, Old Ottawa South & Lansdowne", localNote: "Central Ottawa. Glebe, Old Ottawa South and Lansdowne area." },
  { slug: "beacon-hill", name: "Beacon Hill", desc: "Beacon Hill, Cyrville & Gloucester North", localNote: "East Ottawa. Beacon Hill, Cyrville and north Gloucester." },
  { slug: "blackburn-hamlet", name: "Blackburn Hamlet", desc: "Blackburn Hamlet & Orleans east", localNote: "East Ottawa. Blackburn Hamlet and eastern Orleans." },
  { slug: "cumberland", name: "Cumberland", desc: "Cumberland, Orleans & Navan", localNote: "East Ottawa village. Cumberland and rural Orleans." },
  { slug: "carleton-place", name: "Carleton Place", desc: "Carleton Place & Ottawa Valley", localNote: "Serving Carleton Place and surrounding Ottawa Valley communities." },
];

export const testimonials = [
  { name: "Mike R.", area: "Kanata", stars: 5, date: "January 2026", text: "Called at 11pm when my spring snapped and I couldn't get my car out for work. Tech arrived within 75 minutes and had it fixed in under an hour. Incredible service. Will never use anyone else." },
  { name: "Robert H.", area: "Kanata", stars: 5, date: "February 2026", text: "Door came off the track on a Sunday morning. GDS was at my house within an hour. Fixed, tested, and cleaned up in 90 minutes flat. Couldn't believe how fast and professional it was." },
  { name: "Greg T.", area: "Kanata", stars: 5, date: "December 2025", text: "Great experience from start to finish. Booked online, tech called 30 min ahead, arrived on time with all the parts. Spring replacement done perfectly. Bridlewood area — very fast response." },
  { name: "Sarah T.", area: "Barrhaven", stars: 5, date: "December 2025", text: "Garage door stopped working during a -30°C cold snap. GDS came the same morning, diagnosed the frozen opener, and had us back up in no time. Price was exactly what they quoted." },
  { name: "Linda P.", area: "Barrhaven", stars: 5, date: "January 2026", text: "New door installation looks absolutely stunning. The team was clean, efficient, and finished ahead of schedule. My neighbours keep asking who did it. Worth every penny." },
  { name: "Chris M.", area: "Barrhaven", stars: 5, date: "November 2025", text: "Both torsion springs snapped at the same time. GDS came out same day, replaced both with upgraded hardware and balanced the door perfectly. Half the price I expected." },
  { name: "James L.", area: "Nepean", stars: 5, date: "February 2026", text: "Had 3 quotes to replace my entire door. GDS showed me I only needed a panel and spring, saving me over $1,200. Honest company that puts the customer first." },
  { name: "Christine B.", area: "Nepean", stars: 5, date: "November 2025", text: "Opener stopped working in the middle of winter. GDS came out the same evening, diagnosed a bad logic board, had the part on the truck, and fixed it on the spot. Lifesavers." },
  { name: "Dan W.", area: "Nepean", stars: 5, date: "October 2025", text: "Older home in Bells Corners with an original 90s door system. Tech knew exactly what parts to source, had it running smooth within two hours. Real knowledge of older systems." },
  { name: "Fatima K.", area: "Orleans", stars: 5, date: "November 2025", text: "Excellent service. Quick, professional, and left the workspace spotless. My door works better than new! Highly recommend to anyone in the Orleans area." },
  { name: "Ahmed S.", area: "Orleans", stars: 5, date: "December 2025", text: "Used GDS for a spring replacement and was so impressed I booked a full tune-up the same week. Both techs were polite, knowledgeable, and explained everything clearly. 10/10." },
  { name: "Nadia B.", area: "Orleans", stars: 5, date: "January 2026", text: "Needed an emergency repair on a Saturday night in Fallingbrook. GDS answered immediately and arrived within 90 minutes. Friendly tech, clean work, fair price. Amazing." },
  { name: "Jennifer W.", area: "Stittsville", stars: 5, date: "October 2025", text: "Brand new smart opener installed perfectly. The tech showed me how to use the app, set up guest access for my kids, and even adjusted a spring that was slightly off. Above and beyond." },
  { name: "Mark D.", area: "Stittsville", stars: 5, date: "December 2025", text: "Fastest response I've ever seen from a trades company. Called at 8am, tech was here by 9am. Cable snapped, replaced same visit. Stittsville local — clearly knows the area." },
  { name: "David M.", area: "Gloucester", stars: 5, date: "January 2026", text: "Second time using GDS. Both times: on time, transparent pricing, quality work. They noticed my cables were fraying and showed me before replacing. That proactive approach is rare." },
  { name: "Tom K.", area: "Gloucester", stars: 5, date: "October 2025", text: "Called for an emergency repair at 7am. Tech was at my door by 8:30am. Spring replacement done perfectly. Fair price, no upselling, just honest work. My garage door company for life." },
  { name: "Rachel S.", area: "Gloucester", stars: 5, date: "November 2025", text: "Moved into a new place in South Keys and the door was a mess. GDS did a full tune-up, replaced rollers and weatherstrip. Runs like a dream now and the price was very reasonable." },
  { name: "Maria V.", area: "Manotick", stars: 5, date: "February 2026", text: "Had a large custom door installed for our estate property. GDS handled the whole project professionally from quote to cleanup. Beautiful result and the price was very competitive." },
  { name: "Brian C.", area: "Manotick", stars: 5, date: "January 2026", text: "Rural property with an oversized garage. GDS sourced the right heavy-duty springs, came out on time, and did an immaculate job. Not every company will service out here — they did without hesitation." },
  { name: "Kevin O.", area: "Westboro", stars: 5, date: "January 2026", text: "Old heritage home with a tricky older door system. GDS tech knew exactly what parts to use, sourced them same day, and fixed it properly. Real expertise on older door systems." },
  { name: "Amy H.", area: "Westboro", stars: 5, date: "December 2025", text: "Tight laneway, older garage, weird door size. GDS figured it all out without any drama. Showed up on time, clean work, done in under 2 hours. Best tradie experience I've had in Ottawa." },
  { name: "Diane F.", area: "Hunt Club", stars: 5, date: "December 2025", text: "Commercial unit with a heavy door that needed spring replacement. GDS quoted fairly, arrived on time, and had it done in under 2 hours. Zero disruption to my business." },
  { name: "Paul N.", area: "Riverside South", stars: 5, date: "November 2025", text: "New build home, brand new door that started making grinding noises after 6 months. GDS diagnosed a manufacturer defect, helped with the warranty claim, and fixed it. Outstanding." },
  { name: "Tanya R.", area: "Alta Vista", stars: 5, date: "October 2025", text: "Established neighbourhood, older door that needed full servicing. GDS tech was thorough, replaced all the worn rollers and hinges, lubricated everything. Door is whisper quiet now." },
];

export const faqs = [
  { q: "How much does garage door repair cost in Ottawa?", a: "Spring replacement $220–350, cable repair $170–250, maintenance tune-up $150, panel repair from $170 (we don't replace panels). Opener installation from $195; opener gear replacement from $250; new openers supply & install from $650 (model-dependent). New garage doors from $1,800–4,500 (size and model). We always provide a full written quote before any work begins." },
  { q: "How fast can you respond to an emergency?", a: "We arrive in under 90 minutes everywhere in Ottawa — same promise in every neighbourhood." },
  { q: "Do you offer a warranty on your repairs?", a: "Yes. All parts come with a minimum 1-year warranty and all labour is guaranteed for 90 days. New door installations carry a 5-year warranty." },
  { q: "Can I get same-day service?", a: "Absolutely. Same-day service is available 7 days a week, 9AM–9PM. We stock the most common parts on our trucks so most repairs are completed in one visit." },
  { q: "Are you licensed and insured?", a: "Yes. Ottawa - GDR is fully licensed in Ontario and carries $2 million in liability insurance." },
  { q: "What brands do you work with?", a: "We service all major brands including LiftMaster, Chamberlain, Genie, Craftsman, Marantec, Garaga, Clopay, Wayne Dalton, and more." },
];

/** Gallery: copy images from garagedoorsolutionsottawa.ca/gallery into public/gallery/ as 1.jpg, 2.jpg, etc. Or use full URLs (domain allowed in next.config). */
export const galleryImages = [
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/IMG-20260206-WA0000(1).jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'New insulated garage door Kanata', caption: 'New insulated garage door in Kanata' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/IMG-20260206-WA0001(8).jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Weather stripping garage door Ottawa', caption: 'Weather stripping' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/blob-2c95119.png/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Garage door installed Barrhaven', caption: 'Garage door installed in Barrhaven' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/20251025_142148.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Two garage doors replaced Nepean', caption: '2 doors replaced in Nepean' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/20250124_095313.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'New door and opener Greely', caption: 'New door and opener in Greely' },
  { src: 'https://img1.wsimg.com/isteam/ip/1b277bec-adfe-487a-a8c7-5e77b97e6d1d/20250121_090341.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true', alt: 'Opener gear replacement Ottawa', caption: 'Gear replacement' },
];

export const blogPosts = [
  { slug: "garage-door-repair-cost-ottawa", title: "How Much Does Garage Door Repair Cost in Ottawa? (2026 Guide)", excerpt: "Complete pricing breakdown for every common garage door repair in Ottawa.", date: "February 10, 2026", readTime: "5 min read", category: "Pricing" },
  { slug: "broken-spring-ottawa-what-to-do", title: "Broken Garage Door Spring in Ottawa? Here's What To Do", excerpt: "Step-by-step guide on how to identify a broken spring and stay safe.", date: "January 28, 2026", readTime: "4 min read", category: "DIY Tips" },
  { slug: "garage-door-not-opening-cold-weather", title: "Garage Door Not Opening in Cold Weather? Ottawa Winter Fixes", excerpt: "Ottawa's brutal winters wreak havoc on garage doors. Here's why and how to fix it.", date: "January 15, 2026", readTime: "6 min read", category: "Winter Tips" },
  { slug: "best-insulated-garage-doors-ottawa", title: "Best Insulated Garage Doors for Ottawa Winters (2026 Reviews)", excerpt: "We compare the top insulated garage door brands available in Ottawa.", date: "December 20, 2025", readTime: "7 min read", category: "Buying Guide" },
  { slug: "how-long-do-garage-door-springs-last", title: "How Long Do Garage Door Springs Last? Ottawa Homeowner Guide", excerpt: "Most springs are rated for 10,000 cycles. Find out when to replace before they snap.", date: "December 5, 2025", readTime: "4 min read", category: "Maintenance" },
  { slug: "smart-garage-door-opener-ottawa", title: "Best Smart Garage Door Openers in Ottawa (2026)", excerpt: "We review the top WiFi-enabled openers available and installed in Ottawa.", date: "November 18, 2025", readTime: "8 min read", category: "Smart Home" },
];
